### ISSUE TITLE
💖 welcoming new libvirt maintainers (cores)

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule-libvirt#13]
I am unable to maintain this driver as I am not using it, so I am looking for maintainers. 

I can keep providing support for integration with molecule itself but not around driver specifics.

I would work noting that the top priority would be to setup CI jobs.

**Comment by odyssey4me** [comment]
I'm prepare to pick this up, although I've got limited time so I'd prefer to have some help with it.

**Comment by jamesregis** [comment]
Hello,

I don't know if this message is still relevant but I can propose my contribution to maintain this module.

Regards.

**Comment by ssbarnea** [comment]
You are more than welcome. Please remember to join the irc channel #ansible-molecule - ping me there, my irc nick is zbr.

**Comment by ssbarnea** [comment]
@jamesregis I did send you an invite to this repo, check your email.

**Comment by ssbarnea** [comment]
I also invited @goldyfruit to the project.  I will be on PTO for one week, but I think I managed to bring it to state where you can rely on CI to help you with propose changes.

**Comment by ssbarnea** [comment]
I am archiving this plugin repository. If anyone wants to takeover its maintenance, please start by making a PR to transfer its code into https://github.com/ansible-community/molecule-plugins repository.

This repository will be archived.
